COMP: Fix windows link error adding dependency to VolumeRendering MRML library
This commit fixes a regression introduced in previous commit. It fixes
the following error:

  vtkMRMLNodeSequencer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class vtkMRMLVolumePropertyNode  [...]

Reported-by: Tamas Ungi <ungi@queensu.ca>